ci: build and push the docker image to ghcr
reviewdog/action-detect-secrets pull request #55
Opened 2024-01-30 21:01 UTC by jizusun

2024-01-31 06:49 UTC, levonet requested changes
I want to warn you. Publishing a Docker image and using it from a user repository is not acceptable from a security perspective.
Imagine that I use this action in a closed company repository. Running an opaque container can be used to access closed source code and compromise it.

Community tools should be as transparent as possible from a security point of view.
In this case, an opaque chain with the Docker image is added, which can fall under the control of an attacker.

2024-02-02 19:48 UTC, jizusun commented
> I want to warn you. Publishing a Docker image and using it from a user repository is not acceptable from a security perspective. Imagine that I use this action in a closed company repository. Running an opaque container can be used to access closed source code and compromise it.
> 
> Community tools should be as transparent as possible from a security point of view. In this case, an opaque chain with the Docker image is added, which can fall under the control of an attacker.

Yes, I understand there is a risk in the software supply chain.
But I'm wondering what's the other solution to solve the problem I mentioned in this issue https://github.com/reviewdog/action-detect-secrets/issues/54, that is the actions is slow to start. 

This is why I didn't update the README in this PR.

If somebody want to skip the action build step ( 50s -> 9s), he can check the GHCR to use the prebuilt image after inspecting  whole the built process (all available in open source, no hidden part) rather than build and push by himself, also just like here https://github.com/reviewdog/action-actionlint uses GHCR. 

If somebody is still concerned about the integrity of the docker image, he just used the current way, that is, building the docker image when using the action.

Do you think it is okay for you to accept the PR , and I'll create a follow-up PR to resolve your concern.
My plan is
- Clarify the supply chain problem
- Warn the user the risk
- The current one as the recommend one, and the pre-built approach as an alternative one

2024-02-08 02:57 UTC, jizusun commented
@shogo82148  Can you help to approve the workflow to run?
Sorry that previous workflow failed because of `gcc`

2024-02-08 14:35 UTC, shogo82148 approved these changes

2024-02-13 17:48 UTC, javierjulio commented
In other python based actions like action-yamllint we are using alpine. I use this action and action-yamllint in many repos together. While I've noticed the slowdown, could we not just use the alpine version here too as suggested? I believe that would help. I think that would be safer too.

2024-02-13 18:29 UTC, javierjulio requested changes
@jizusun thank you. I agree with @levonet we should avoid pushing the image for now. There is no need to do this as by just using alpine we should see a faster start time in workflow runs. I encountered the same slowness at times. I would accept just the alpine change for now.

2024-02-13 18:29 UTC, javierjulio commented on .github/workflows/docker-build.yml
Let's remove this file for now. We don't need to do this to improve the action run time.

2024-02-13 18:29 UTC, javierjulio commented on Dockerfile
> +    && pip install detect-secrets[word_list]
Avoid unnecessary changes. This space was added here. 

```suggestion
    && pip install detect-secrets[word_list]
```

2024-02-13 18:29 UTC, javierjulio commented on Dockerfile
> +RUN apk --no-cache add git gcc musl-dev \
Was gcc and musl-dev only added for the docker push workflow? If so, then let's make sure to remove these, please.

```suggestion
RUN apk --no-cache add git \
```

2024-06-08 10:21 UTC, haya14busa commented
Can somebody create a pr to change the image to alpine or slim?

2024-08-22 15:07 UTC, javierjulio commented
Yes, a new PR was created in #71 which looks good.

2024-08-22 15:07 UTC, closed without merging